AllCops:
  NewCops: enable
Layout/LineLength:
  Max: 99
Metrics/ClassLength:
  Enabled: false
Lint/LiteralAsCondition:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false
Naming/RescuedExceptionsVariableName:
  Enabled: false

Style/StringLiterals:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/EvalWithLocation:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/SignalException:
  Enabled: false
